### ISSUE TITLE
incorrect git Link in Readme.md

### ISSUE THREAD

**Issue by justiceotuya** [BolajiOlajide/UserManager#14]
The repo link in the readme.MD file is incorrect and as such users cannot clone the link via the provided link.
the link is 
git clone https://github.com/andela-bolajide/UserManager 
instead of https://github.com/BolajiOlajide/UserManager.git

**Comment by BolajiOlajide** [comment]
Thanks @justiceotuya 
I've fixed it.

Cheers!
